all:
	mkdir bin
	gcc -o bin/main src/main.c
	gcc -o bin/sum src/sum.c
	gcc -o bin/sub src/sub.c
	gcc -o bin/mul src/mul.c
	gcc -o bin/div src/div.c
	gcc -o bin/min src/min.c
	gcc -o bin/max src/max.c
	gcc -o bin/help src/help.c
clean:
	rm -rf bin